#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'application_python',
   :git => 'https://github.com/opscode-cookbooks/application_python',
   :ref => '1.2.4'

cookbook 'django_application',
   :git => 'https://github.com/flaccid/cookbooks',
   :path => 'cookbooks/django_application',
   :ref => 'master'

# add version control cookbooks
cookbook 'git',
   :git => 'https://github.com/opscode-cookbooks/git',
   :ref => '2.5.0'

cookbook 'mercurial',
   :git => 'https://github.com/opscode-cookbooks/mercurial',
   :ref => '1.1.4'

cookbook 'subversion',
   :git => 'https://github.com/opscode-cookbooks/subversion',
   :ref => '1.0.2'